# Generated by Django 4.2.28 on 2026-02-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_enhanced_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-created_at"], "verbose_name": "Task", "verbose_name_plural": "Tasks"},
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="task_user_status_del_idx",
            old_name="task_usr_stat_del_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="task_priority_due_del_idx",
            old_name="task_pri_due_del_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="task_user_created_del_idx",
            old_name="task_usr_crt_del_idx",
        ),
        migrations.RenameIndex(
            model_name="taskhistory",
            new_name="task_history_task_time_idx",
            old_name="task_hist_tsk_tm_idx",
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, help_text="Detailed task description"),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(blank=True, db_index=True, help_text="Task deadline", null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                db_index=True,
                default="MEDIUM",
                help_text="Task priority level",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("TODO", "To Do"), ("DOING", "Doing"), ("DONE", "Done")],
                db_index=True,
                default="TODO",
                help_text="Current status of the task",
                max_length=10,
            ),
        ),
    ]
